/**
 * mimacom Banking API
 * This is a sample API used to illustrate the tooling around an API-first approach.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: andreas.hirsch@mimacom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';


export interface GetAccountsResponse { 
    items?: Array<Account>;
}


